### ISSUE TITLE
Extra '(' to be removed

### ISSUE THREAD

**Issue by josepho0918** [ARM-software/CMSIS_6#116]
There's an extra '(' at line 621 in cmsis_iccarm_m.h file.
```
  #if !((defined (__ARM_FP)      && (__ARM_FP >= 1)) 
    #undef __get_FPSCR
    #undef __set_FPSCR
    #define __get_FPSCR()       (0)
    #define __set_FPSCR(VALUE)  ((void)VALUE)
  #endif
```

**Comment by GuentherMartin** [comment]
Hello @josepho0918, thank you for pointing out.

**Comment by GuentherMartin** [comment]
Hi @josepho0918, could you please verify the fix.

**Comment by josepho0918** [comment]
> Hi @josepho0918, could you please verify the fix.

Hi @GuentherMartin, verified.🙂
