### ISSUE TITLE
CoreDebug_Type no longer defined

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/CMSIS_6#118]
CMSIS 5.9 did define `CoreDebug_Type` that is used by `fsl_common.c` and therefore affects many NXP projects.

With CMSIS 6.0 this symbol has been renamed to `DCB_Type`.

There is no information about this renaming and https://learn.arm.com/learning-paths/microcontrollers/project-migration-cmsis-v6/troubleshooting/ does not mention it either.  Has there been an impact analysis?  How many DFPs depend on `CoreDebug_Type`?

Test project: https://github.com/Open-CMSIS-Pack/csolution-examples/tree/main/DualCore

**Comment by JonatanAntoni** [comment]
Addressed by #122
