### ISSUE TITLE
CoreDebug_Type no longer defined

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/CMSIS_6#119]
CMSIS 5.9 did define CoreDebug_Type.
CMSIS 6.0 replaces this by DCB_Type.

NXP is using this symbol in their DFPs (file fsl_common_arm.c).  Has there been an impact analysis?  How many DFPs are affected?

https://learn.arm.com/learning-paths/microcontrollers/project-migration-cmsis-v6/troubleshooting/ does not mention that problem.

CMSIS-Core history does also not cover details.  The reference to 'TRM' is a bit cryptic.

Example Project: https://github.com/Open-CMSIS-Pack/csolution-examples/tree/main/DualCore

**Comment by JonatanAntoni** [comment]
Duplicates #118
