### ISSUE TITLE
CMSIS API to obtain fine grained caching information

### ISSUE THREAD

**Issue by redbilledpanda** [ARM-software/CMSIS_6#133]
Hello

I have been looking around CMSIS APIs to obtain fine grained information about caching. I am specifically looking at the MSMP0 (Arm Cortex M0, v6 arch) family of MCUs so I may be biased in that direction. What I am looking for is the kind of information available from Texas Instrument's DriverLib function ['DL_CORE_getInstructionConfig'](https://software-dl.ti.com/msp430/esd/MSPM0-SDK/1_20_00_05/docs/english/driverlib/mspm0c110x_api_guide/html/dl__core_8h.html#a391d1d42cdc53a20949bf472a64ebda9). 

As of now I couldn't find anything that will return instruction caching, prefetch, and 'literal cache' configuration. I looked at "MPU functions for Armv6-M/v7-M" as well as Cache functions [Level-1] but nothing maps to what I need. Is there something that I can use as a sort of a workaround or perhaps I'm missing something here? Perhaps we need more than a single function to get to this information?

**Comment by JonatanAntoni** [comment]
Hi @redbilledpanda,

Did you already try to get in touch with the TI community?
The API functions you are referring to are not part of CMSIS.

The Arm Cortex-M0+ processor does not have a built-in cache. Hence, the CMSIS cache functions do not apply.

**Comment by redbilledpanda** [comment]
Hello @JonatanAntoni 

Of course not but I was wondering if a driver for this family is in the works. Of course for now I will stick to the TI specified solution however would be great to use it via a unified API layer that lands into this driver.

**Comment by JonatanAntoni** [comment]
A unification in this area is very unlikely to happen. As I said above, this is a very TI specific feature. Hence, I expect a TI specific API and implementation is required which probably won't match any other Cortex-M0+-based device from other vendors.

**Comment by redbilledpanda** [comment]
Understood. Thanks a bunch
