### ISSUE TITLE
__ARM_ARCH_8_1M_MAIN__ is not documented

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/CMSIS_6#160]
I believe that with ArmV8.1M a new macro has been added to CMSIS: `__ARM_ARCH_8_1M_MAIN__ `.  This is not covered in the current documentation.

Also the value of `__ARM_ARCH_8M_xxxx` seems to be compiler dependent as CMSIS only defines fallbacks. Maybe this is worth a note. See also the problem described in #159

**Comment by vovamarch** [comment]
Added description of __ARM_ARCH_8_1M_MAIN__  in https://github.com/ARM-software/CMSIS_6/pull/162 .
