### ISSUE TITLE
trustzone applications can be secure-only

### ISSUE THREAD

**Issue by jeromecoutant** [ARM-software/CMSIS_6#203]
Hi

See https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#processor

A secure application can be "secure" or "secure-only"

So at https://github.com/ARM-software/CMSIS_6/blob/main/ARM.CMSIS.pdsc#L624
Shouldn't we update:
```
<require Dsecure="Secure"/>
```
into?
```
  <accept Dsecure="Secure"/>
  <accept Dsecure="Secure-only"/>
```

**Comment by JonatanAntoni** [comment]
Hi @jeromecoutant,

It looks like that has been overlooked once adding the `Secure-only` option two month ago.

The impact should be minor as the only instance this condition is used for is for selecting which templates are offered by CMSIS-Core component.

Hence, I'd agree adding it shouldn't harm. Would you volunteer raising the required PR?
