### ISSUE TITLE
Tentative date for production release?

### ISSUE THREAD

**Issue by renesas-brandon-hussey** [ARM-software/CMSIS_6#50]
I see there is a dev drop already. Is there a rough plan for when the final 6.0.0 will be ready?

**Comment by JonatanAntoni** [comment]
Hi @renesas-brandon-hussey, 

We don't have an agreed release date, yet. We need to be careful and keep the related packs in sync. An outstanding issue we need to solve prior the release is about default linker script handling, see Open-CMSIS-Pack/devtools#1134.

**Comment by renesas-brandon-hussey** [comment]
Thanks, this is the information I needed.
