### ISSUE TITLE
Unknown pragma when compiling with GCC

### ISSUE THREAD

**Issue by renesas-kyle-finch** [ARM-software/CMSIS_6#59]
I pulled down the latest dev drop today. 

It appears there is a `clang` pragma in `cmsis_gcc_m.h` (maybe others too) that generates a build error.
![image](https://github.com/ARM-software/CMSIS_6/assets/139795925/27d27f66-b8e4-42e1-8695-90b520e6ca31)

If I delete this line, then it builds fine

**Comment by JonatanAntoni** [comment]
Thanks for reporting this. I'd assume GCC to ignore pragmas for other compilers. Which version of GCC do you use?

In this case, the pragma got added long time ago when the only way to use Clang was via GCC compatibility. Nowadays, we have separate headers for Clang and could (probably should) remove these pragmas from GCC headers.

Would you like to contribute the changes that via pull-request?

**Comment by finchky** [comment]
We are using ARM GNU Toolchain 12.2. And are treating warnings as errors.

Sure, I can make a pull-request
